### ISSUE TITLE
Missing csproj in src

### ISSUE THREAD

**Issue by valkyrienyanko** [LauraWebdev/SofiaConsole#1]
Is it possible for you to add `.csproj` to `Src\sofiaconsole`? If not, not a big deal.

**Comment by LauraWebdev** [comment]
It's the same as [this one](https://github.com/LauraWebdev/SofiaConsole/blob/main/demo/SofiaConsole.csproj) as I use the demo project for dev, but I'll try and see if I can couple it out more properly.
