### ISSUE TITLE
Default Language in config file

### ISSUE THREAD

**Issue by hbdermott** [LauraWebdev/SofiaConsole#3]
HI! Thank you so much for making this, it saved me a bunch of work and it looks amazing!

Two really small nitpicks that threw me off at first
- The plugin.cfg file does not have a default language set of C# (Godot seems to thing the plugin should be added as GDScript)
- The README file steps don't mention that you have to build your project after you add it to the addons folder

Again, thank you so much for this!

**Comment by LauraWebdev** [comment]
This should be fixed now.
